name: location
description: A Flutter library for fingerprint matching and location view.
version: 0.1.0
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.5.3
  wifi_scan: ^0.4.1
  flutter_blue_plus: 1.35.3

dev_dependencies:
  flutter_test:
    sdk: flutter
